#!/usr/bin/env bash

echo "Initializing SSH agent..."
eval `ssh-agent -s`
echo "Authorizing GitHub key on keyring..."
ssh-add ~/.ssh/keys/id_rsa_github

echo "You can use git commands with remotes now :)" | cowsay
